// <auto-generated />
namespace ConsoleApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedSteamAppId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedSteamAppId));
        
        string IMigrationMetadata.Id
        {
            get { return "201607071231331_addedSteamAppId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
